# Рабочая тетрадь № 2
## Лосев Антон ИКБО-02-21

### 1.2.1 Пример
Создать массив 5x2. Вывести все значения массива,значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум,максимум и среднее значение

In [5]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004931245697480602 0.998096316242425 0.4376471810102778


### 1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.


In [3]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Выяснить результат следующих выражений:\
0 * np.nan\
np.nan == np.nan\
np.inf > np.nan\
np.nan - np.nan\
0.3 == 3 * 0.1

In [7]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Отсортировать массив.

In [8]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [9]:
A = np.arange(64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        A[i][j] = (i + j) & 1

print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [26]:
A = np.arange(25).reshape(5, 5) % 5
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [15]:
A = np.random.random((3, 3, 3))
print(A)

[[[0.24138309 0.73102265 0.2670937 ]
  [0.75960513 0.52099017 0.52930855]
  [0.5713842  0.9777403  0.20617396]]

 [[0.09307583 0.76631111 0.18083544]
  [0.17749388 0.17428197 0.61708913]
  [0.8698469  0.29053838 0.81579476]]

 [[0.39783237 0.45699435 0.95174257]
  [0.97462563 0.71307295 0.66939808]
  [0.94912181 0.50121343 0.67249087]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [16]:
A = np.ones((10, 10))
A[1:-1, 1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [28]:
arr = np.random.randint(0, 10, 10)
arr[::-1].sort()
print(arr)

[9 8 8 7 4 1 1 1 0 0]


### 1.3.6 Задние
Создайте матрицу, выведите ее форму, размер и размерность.

In [31]:
import numpy as np

arr = np.random.randint(0, 10, (3, 3, 3))
print(f'Размерность {arr.shape} \nРазмер: {arr.size}')

Размерность (3, 3, 3) 
Размер: 27


### 2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего). 

In [35]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)


0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [44]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


### 2.2.3 Пример
Создайте новый фрейм данных.


In [45]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [50]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

### 2.2.5 Пример
Пронализировать характеристики фрейма данных.


In [52]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [54]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [56]:
dataframe.shape

(1313, 6)

In [57]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

### 2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных.

In [58]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### 2.2.7 Пример
Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса

In [59]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### 2.3.1 Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [77]:
def dist(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

a = pd.Series(np.arange(1, 3))
b = pd.Series(np.arange(3, 5))
print(dist(a, b))

2.8284271247461903


### 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных 

In [79]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'

dataframe = pd.read_csv(url)
dataframe

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [80]:
dataframe.head(2)

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian

In [81]:
dataframe.tail(3)

stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal

In [82]:
dataframe.shape

(7, 4)

In [83]:
dataframe.describe()

stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3

In [84]:
dataframe.iloc[1:4]

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal

In [85]:
dataframe[dataframe['slope'] == 'steep']

stream  slope elevation vegetation
0   False  steep      high  chapparal
2    True  steep    medium   riparian
3   False  steep    medium  chapparal
5    True  steep   highest    conifer
6    True  steep      high  chapparal

### 3.2.1 Пример
Прошкалируйте числовой признак в диапазон между двумя значениями

In [88]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2 Пример
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [91]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

print('Среднее: ', round(standardized.mean()))
print('Стандартное отклонение', standardized.std())

Среднее:  0
Стандартное отклонение 1.0


### 3.2.3 Пример
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],\
 'B':[103.02,107.26,110.35,114.23,114.68],\
 'C':['big','small','big','small','small']}) \
Необходимо масштабировать его числовые столбцы.

In [92]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание
Загрузить фрейм данных по ссылке:\
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.\
Необходимо выполнить нормализацию первого числового признака(sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [97]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)
dataframe['sepal_length_cm'] = MinMaxScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe['sepal_width_cm']  = StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.625000        1.032057              1.4             0.2   
1           0.416667       -0.124958              1.4             0.2   
2           0.500000        0.337848              1.3             0.2   
3           0.458333        0.106445              1.5             0.2   
4           0.666667        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.416667       -0.124958              5.2             2.3   
146         0.208333       -1.281972              5.0             1.9   
147         0.416667       -0.124958              5.2             2.0   
148         0.583333        0.800654              5.4             2.3   
149         0.416667       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]